Repository orionalfa/node-develop-your-mvc-project, pull requests merged in 2021-09, with the labels that each got.

#30 populate the models into products
  Backend/src/controllers/product-controller.js
  Backend/src/models/product-model.js
Labels: feat

#31 B users model
  Backend/src/controllers/index.js
  Backend/src/controllers/user-controller.js
  Backend/src/index.js
  Backend/src/models/index.js
  Backend/src/models/user-model.js
  Backend/src/routes/index.js
  Backend/src/routes/user-router.js
  Backend/src/server.js
Labels: feat

#33 Front/feat read products
  Backend/src/server.js
  Frontend/public/img/logotype.png
  Frontend/public/img/mockProduct.JPG
  Frontend/public/img/portadaGuitarra.jpeg
  Frontend/public/img/violin.jpg
  Frontend/src/Pages/Products/ProductPage.js
  Frontend/src/components/productItem/ProductItem.js
  Frontend/src/components/productItem/styles.css
  package-lock.json
Labels: feat

#34 Fix develop merge
  Backend/package-lock.json
  Backend/src/index.js
  Frontend/src/Pages/Home/homePage.js
  Frontend/src/Pages/Home/homeStyles.css
  Frontend/src/Pages/Home/portadaGuitarra.jpeg
  Frontend/src/components/Cart/Cart.js
  Frontend/src/components/NavBar/NavBar.js
Labels: fix

#36 Feat/login modal
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/img/portadaGuitarra.jpeg
  Frontend/src/App.css
  Frontend/src/App.js
  Frontend/src/Pages/Home/homePage.js
  Frontend/src/Pages/Home/homeStyles.css
  Frontend/src/Pages/ProductDashboard/ProductDashboard.js
  Frontend/src/Pages/ProductDashboard/index.js
  Frontend/src/Pages/ProductDashboard/styles.css
  Frontend/src/Pages/SignUp/SignUpPage.js
  Frontend/src/components/LogIn/LogIn.js
  Frontend/src/components/LogIn/index.js
  Frontend/src/components/LogIn/styles.css
  Frontend/src/components/NavBar/NavBar.js
  Frontend/src/components/NavBar/styles.css
  Frontend/src/index.css
Labels: feat

#37 Trying reduce
  Frontend/src/App.js
  Frontend/src/Pages/ProductDashboard/ProductDashboard.js
  Frontend/src/Pages/Products/ProductPage.js
  Frontend/src/Pages/SignUp/SignUpPage.js
  Frontend/src/components/Cart/Cart.js
  Frontend/src/context/context.js
  Frontend/src/context/index.js
Labels: feat

#43 Fix/grid size
  Frontend/src/Pages/Checkout/ConfirmOrder/ConfirmOrder.js
  Frontend/src/Pages/Checkout/ConfirmOrder/index.js
  Frontend/src/Pages/Checkout/ConfirmOrder/styles.css
  Frontend/src/Pages/Checkout/PaymentMethod/PaymentMethod.js
  Frontend/src/Pages/Checkout/PaymentMethod/index.js
  Frontend/src/Pages/Checkout/PaymentMethod/styles.css
  Frontend/src/Pages/Checkout/PreviewOrder/PreviewOrder.js
  Frontend/src/Pages/Checkout/PreviewOrder/index.js
  Frontend/src/Pages/Checkout/PreviewOrder/styles.css
  Frontend/src/Pages/Checkout/ShippingInfo/ShippingInfo.js
  Frontend/src/Pages/Checkout/ShippingInfo/index.js
  Frontend/src/Pages/Checkout/ShippingInfo/styles.css
  Frontend/src/Pages/Checkout/ShippingMethod/ShippingMethod.js
  Frontend/src/Pages/Checkout/ShippingMethod/index.js
  Frontend/src/Pages/Checkout/ShippingMethod/styles.css
  Frontend/src/Pages/ProductDashboard/ProductDashboard.js
  Frontend/src/Pages/Products/ProductPage.js
Labels: fix, feat

#46 B product controller: update, delete and create product
  Backend/src/controllers/index.js
  Backend/src/controllers/model-controller.js
  Backend/src/controllers/product-controller.js
  Backend/src/models/index.js
  Backend/src/models/model-model.js
  Backend/src/models/product-model.js
  Backend/src/routes/index.js
  Backend/src/routes/model-router.js
  Backend/src/routes/product-router.js
  Backend/src/server.js
  Backend/src/utils/generate-response.js
Labels: feat

#49 B product controller: Crud of Models
  Backend/src/controllers/model-controller.js
  Backend/src/routes/model-router.js
Labels: feat

#51 Feat/checkout shipping info view
  Frontend/src/Pages/Checkout/ShippingInfo/ShippingInfo.js
  Frontend/src/Pages/Checkout/ShippingInfo/styles.css
  Frontend/src/Pages/Checkout/ShippingMethod/ShippingMethod.js
  Frontend/src/components/Cart/Cart.js
  Frontend/src/components/CheckoutFooter/CheckoutFooter.js
  Frontend/src/components/CheckoutFooter/index.js
  Frontend/src/components/CheckoutFooter/styles.css
  Frontend/src/index.css
Labels: feat

#52 feat: shipping method view done
  Frontend/src/Pages/Checkout/ConfirmOrder/styles.css
  Frontend/src/Pages/Checkout/PaymentMethod/styles.css
  Frontend/src/Pages/Checkout/PreviewOrder/styles.css
  Frontend/src/Pages/Checkout/ShippingInfo/ShippingInfo.js
  Frontend/src/Pages/Checkout/ShippingInfo/styles.css
  Frontend/src/Pages/Checkout/ShippingMethod/ShippingMethod.js
  Frontend/src/Pages/Checkout/ShippingMethod/styles.css
  Frontend/src/Pages/Checkout/styles.css
Labels: feat

#53 added remaining fields to register form
  Frontend/package-lock.json
  Frontend/src/Pages/SignUp/SignUpPage.js
  Frontend/src/Pages/SignUp/styles.css
Labels: fix

#54 Front/feat delete product
  Backend/src/controllers/product-controller.js
  Frontend/src/App.js
  Frontend/src/Pages/ProductDashboard/ProductDashboard.js
Labels: feat

#56 Fb feat login
  Backend/package-lock.json
  Backend/package.json
  Backend/src/controllers/user-controller.js
  Backend/src/routes/user-router.js
  Backend/src/utils/encrypt.js
  Frontend/src/Pages/SignUp/SignUpPage.js
  Frontend/src/Pages/SignUp/styles.css
Labels: feat

#63 feat: loout button
  Frontend/src/components/LogIn/LogIn.js
Labels: feat

#64 FB-feat-Login
  Frontend/src/components/LogIn/LogIn.js
Labels: feat

#65 Fixing login
  Frontend/src/Pages/SignUp/SignUpPage.js
  Frontend/src/components/LogIn/LogIn.js
Labels: fix

#67 F checkout context
  Frontend/src/App.js
  Frontend/src/Pages/Checkout/ConfirmOrder/ConfirmOrder.js
  Frontend/src/Pages/Checkout/PaymentMethod/PaymentMethod.js
  Frontend/src/Pages/Checkout/PreviewOrder/PreviewOrder.js
  Frontend/src/Pages/Checkout/ShippingInfo/ShippingInfo.js
  Frontend/src/Pages/Checkout/ShippingMethod/ShippingMethod.js
  Frontend/src/context/context.js
Labels: feat

#68 Fixing login
  Backend/src/controllers/user-controller.js
  Backend/src/models/user-model.js
  Frontend/src/Pages/SignUp/SignUpPage.js
  Frontend/src/components/LogIn/LogIn.js
Labels: fix, feat

#69 Users dashboard
  Frontend/src/App.js
  Frontend/src/Pages/SignUp/.SignUpPage.js.swp
  Frontend/src/Pages/SignUp/SignUpPage.js
  Frontend/src/Pages/UsersDashboard/index.js
  Frontend/src/Pages/UsersDashboard/styles.css
  Frontend/src/Pages/UsersDashboard/userDashboard.js
  Frontend/src/components/NavBar/NavBar.js
Labels: feat

#70 F checkout context
  Frontend/src/Pages/Checkout/PreviewOrder/PreviewOrder.js
  Frontend/src/Pages/Checkout/ShippingInfo/ShippingInfo.js
  Frontend/src/Pages/Checkout/ShippingMethod/ShippingMethod.js
  Frontend/src/components/CheckoutItem/CheckoutItem.js
  Frontend/src/components/CheckoutItem/index.js
  Frontend/src/components/CheckoutItem/styles.css
  Frontend/src/components/CheckoutResume/CheckoutResume.js
  Frontend/src/components/CheckoutResume/index.js
  Frontend/src/components/CheckoutResume/styles.css
Labels: feat

#73 Feat/soppinh cart done
  Backend/src/index.js
  Frontend/src/App.js
  Frontend/src/components/Cart/Cart.js
  Frontend/src/components/Cart/styles.css
  Frontend/src/components/CartItem/CartItem.js
  Frontend/src/components/productItem/ProductItem.js
  Frontend/src/components/productItem/styles.css
Labels: fix

#74 Users dashboard
  Backend/src/controllers/product-controller.js
  Backend/src/controllers/user-controller.js
  Backend/src/models/user-model.js
  Frontend/src/App.js
  Frontend/src/Pages/SignUp/.SignUpPage.js.swp
  Frontend/src/Pages/UsersDashboard/index.js
  Frontend/src/Pages/UsersDashboard/styles.css
  Frontend/src/Pages/UsersDashboard/stylesUser.css
  Frontend/src/Pages/UsersDashboard/userDashboard.js
  Frontend/src/Pages/updateUser/index.js
  Frontend/src/Pages/updateUser/styles.css
  Frontend/src/Pages/updateUser/updateUserForm.js
Labels: feat

#75 fix: button style fixed
  Frontend/src/Pages/UsersDashboard/stylesUser.css
  Frontend/src/Pages/UsersDashboard/userDashboard.js
Labels: fix

#76 feat: checkout redirect to user info
  Frontend/src/components/Cart/Cart.js
  Frontend/src/components/Cart/styles.css
Labels: feat
