Repository orionalfa/node-develop-your-mvc-project, pull requests merged in 2021-08, with the labels that each got.

#2 Create file structure
  .all-contributorsrc
  .babelrc
  .eslintignore
  .eslintrc.js
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .husky/pre-push
  .lintstagedrc.js
  .prettierrc
  Backend/package-lock.json
  Backend/package.json
  Backend/src/config/config.js
  Backend/src/config/index.js
  Backend/src/db/connect.js
  Backend/src/index.js
  Backend/src/server.js
  Frontend/README.md
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/favicon.ico
  Frontend/public/index.html
  Frontend/public/logo192.png
  Frontend/public/logo512.png
  Frontend/public/manifest.json
  Frontend/public/robots.txt
  Frontend/src/App.css
  Frontend/src/App.js
  Frontend/src/App.test.js
  Frontend/src/index.css
  Frontend/src/index.js
  Frontend/src/logo.svg
  Frontend/src/reportWebVitals.js
  Frontend/src/setupTests.js
  LICENSE
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/server.test.js
  src/index.js
  src/server.js
Labels: enhancement

#10 Frontend
  Backend/package.json
  Backend/src/controllers/index.js
  Backend/src/middlewares/index.js
  Backend/src/models/index.js
  Backend/src/routes/index.js
  Backend/src/services/index.js
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.js
  Frontend/src/index.css
  Frontend/src/index.js
Labels: feat

#11 test
  Frontend/src/App.js
Labels: feat

#13 Basic grid structure
  Frontend/src/App.js
  Frontend/src/Pages/Products/ProductPage.js
  Frontend/src/Pages/Products/index.js
  Frontend/src/Pages/Products/styles.css
Labels: feat

#14 Front/feat product component 2
  Frontend/src/App.js
  Frontend/src/compenents/productItem/ProductItem.js
  Frontend/src/compenents/productItem/index.js
  Frontend/src/compenents/productItem/productItemStyles.css
  Frontend/src/img/violin.jpg
Labels: feat

#15 Front/feat aside shopping cart2
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.js
  Frontend/src/components/Cart/Cart.js
  Frontend/src/components/Cart/cartStyles.css
  Frontend/src/components/Cart/index.js
  Frontend/src/components/CartItem/CartItem.js
  Frontend/src/components/CartItem/cartItemStyles.css
  Frontend/src/components/CartItem/index.js
  Frontend/src/components/NavBar/NavBar.js
  Frontend/src/components/NavBar/index.js
  Frontend/src/components/NavBar/navbarStyles.css
  Frontend/src/img/mockProduct.JPG
  Frontend/src/index.js
  package-lock.json
  package.json
Labels: feat

#16 moved productItem to components folder
  Frontend/src/Pages/Products/ProductPage.js
  Frontend/src/components/productItem/ProductItem.js
  Frontend/src/components/productItem/index.js
  Frontend/src/components/productItem/productItemStyles.css
Labels: fix

#18 basic views for createUserAccount and changeUserPwd
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.js
  Frontend/src/Pages/ChangePwd/ChangePasswordPage.js
  Frontend/src/Pages/ChangePwd/index.js
  Frontend/src/Pages/ChangePwd/styles.css
  Frontend/src/Pages/Products/ProductPage.js
  Frontend/src/Pages/SignUp/SignUpPage.js
  Frontend/src/Pages/SignUp/index.js
  Frontend/src/Pages/SignUp/styles.css
  Frontend/src/components/Input/Input.js
  Frontend/src/components/Input/index.js
  Frontend/src/components/Input/styles.css
  Frontend/src/index.js
Labels: feat

#19 Front/home
  Frontend/package-lock.json
  Frontend/src/App.css
  Frontend/src/App.js
  Frontend/src/components/Home/homePage.js
  Frontend/src/components/Home/homeStyles.css
  Frontend/src/components/Home/index.js
  Frontend/src/components/NavBar/NavBar.js
  Frontend/src/components/NavBar/navbarStyles.css
  Frontend/src/img/portadaGuitarra.jpeg
  package-lock.json
  package.json
Labels: feat

#21 Fix/shopping cart navbar
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.js
  Frontend/src/Pages/Products/ProductPage.js
  Frontend/src/Pages/Products/styles.css
  Frontend/src/components/Cart/Cart.js
  Frontend/src/components/Cart/cartStyles.css
  Frontend/src/components/Cart/styles.css
  Frontend/src/components/CartItem/CartItem.js
  Frontend/src/components/CartItem/cartItemStyles.css
  Frontend/src/components/CartItem/styles.css
  Frontend/src/components/NavBar/NavBar.js
  Frontend/src/components/NavBar/navbarStyles.css
  Frontend/src/components/NavBar/styles.css
Labels: fix
